name: Build

on: [push, pull_request]

jobs:
  windows:
    name: Build (${{ matrix.os }} - ${{ matrix.type }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2016, windows-2019]
        type: [Debug, Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S . -B build
      - name: Build ${{ matrix.type }}
        run: cmake --build build --config ${{ matrix.type }}
      - name: Test ${{ matrix.type }}
        run: |
          cd build
          ctest -C ${{ matrix.type }}
